### ISSUE TITLE
Task.37 - Create unit tests for displaying group details from teacher view

### ISSUE THREAD

**Issue by sasha-klnd** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#106]
Develop comprehensive unit tests to verify the functionality of fetching and displaying group details on the Teach View page. This involves writing test cases to ensure that the relevant API or database calls are correctly retrieving the required group information and that this data is accurately displayed to users on the Teach View interface.

**Comment by Marian-Hristov** [comment]
Closed in #101

**Comment by Marian-Hristov** [comment]
Closed in #101

**Comment by Vinuyans** [comment]
linked to wrong PR
