### ISSUE TITLE
Task.27 AT.02 - Create Acceptance Test for US.02

### ISSUE THREAD

**Issue by sasha-klnd** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#65]
US.02 states that teachers should be able to login to the webpage.

Acceptance tests for this feature include, but may not be limited to, tests that verify:
 - The database rejects a login attempt with an invalid username
 - The database rejects a login attempt with an invalid password
 - When login data is valid, the database returns a non-null (i.e. non-falsy) object
 - When login data is valid, the database returns the correct teacher object, given a hard-coded teacher object with known username and password fields

**Comment by Vinuyans** [comment]
Linked with User Story #2
