### ISSUE TITLE
Task.24 - Rating button

### ISSUE THREAD

**Issue by Marian-Hristov** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#69]
Add a rating a button for a student to rate another student in their group on a scale from 1 to 7.

When student A clicks on student B while viewing their group they should have the ability to rate them on a scale of 1-7.

**Comment by Vinuyans** [comment]
Create a rating modal with:
5-point scale for each of these criteria and a comment box for each of those criteria:
- Cooperation dimension
- Conceptual Contribution
- Practical Contribution
- Work Ethic
