### ISSUE TITLE
Task.31 AT.03- Students adding themselves to courses

### ISSUE THREAD

**Issue by JenLys** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#83]
Make sure that when the user clicks on the View Team Button the list of teammates as well as the Rate button appear

**Comment by JenLys** [comment]
Feature: interface for the student, box displaying names and the rating button

**Comment by sasha-klnd** [comment]
Tests should ensure that:
 - The student home page displays a button for students to add themselves to courses
 - Submitting the form inserts the student's ID to the course's students array

**Comment by Vinuyans** [comment]
Linked with User Story #3

**Comment by Marian-Hristov** [comment]
Closed in #101
