### ISSUE TITLE
Task.32 AT.04 - viewing the students' teams on the teacher's side feature

### ISSUE THREAD

**Issue by srabm** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#85]
Acceptance test for the teacher's side:
- Ensure that the "view teams" button shows all the teams of students
- The interface should contain all the groups within a course
- The interface should also contain the student ids of all the students in a group
- The group names should be unique

**Comment by Vinuyans** [comment]
Linked with User Story 4 #4

**Comment by Marian-Hristov** [comment]
Closed in #101
