### ISSUE TITLE
Task.33 AT.05 - Students reviewing each other feature

### ISSUE THREAD

**Issue by sasha-klnd** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#94]

**Comment by sasha-klnd** [comment]
Acceptance test for the student's side:

- Ensure that the group view correctly displays all the students in the group
- Ensure that the "Rate" button opens the rating modal 
- Ensure that the "Submit" button opens a confirmation popup
- Ensure that an invalid rating (request body with errors) is rejected
- Ensure that a valid rating is accepted

**Comment by Vinuyans** [comment]
Linked with User Story #37
